version: "3.7"

services:
  mysql-master:
    image: mysql-master
    build:
      context: docker/master
      dockerfile: Dockerfile
    env_file:
      - .env

  mysql-slaver:
    image: mysql-slaver
    build:
      context: docker/slaver
      dockerfile: Dockerfile
    env_file:
      - .env
