#!/bin/bash

export MYSQL_PWD=${MYSQL_ROOT_PASSWORD}
mysql -uroot -e \
      "
      STOP SLAVE;
      CHANGE MASTER TO GET_MASTER_PUBLIC_KEY=1;
      CHANGE MASTER TO MASTER_HOST='${MYSQL_MASTER_SERVICE_HOST}', MASTER_USER='${MYSQL_REPLICATION_USER}', MASTER_PASSWORD='${MYSQL_REPLICATION_PASSWORD}';
      START SLAVE;
      "

mysql -uroot -e "SHOW SLAVE STATUS\G;"
