volumes:
    - name: gitlab-runners-cache
      persistentVolumeClaim:
        claimName: gitlab-runners-cache-pvc

rbac:
  create: true
  serviceAccount: gitlab-runner
serviceAccount:
  create: true
  name: gitlab-runner

runners:
  config: |
    [[runners]]
      cache_dir = "/cache"
      clone_url = "{{.Values.gitlabUrl}}"
      [runners.kubernetes]
      namespace = "{{.Release.Namespace}}"
      image = "alpine"
      pull_policy = "if-not-present"
      [runners.cache]
        shared = true
        type = "s3"
        [runners.cache.s3]
          ServerAddress = "{{.Values.s3ServerAddress}}"
          Insecure = true
          AccessKey = "{{.Values.s3AccessKey}}"
          SecretKey = "{{.Values.s3SecretKey}}"
          BucketName = "{{.Values.s3BucketName}}"
    [[runners.kubernetes.volumes.pvc]]
      name = "gitlab-runners-cache-pvc"
      mount_path = "/cache"
