apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
        - name: mysql-master
          image: mysql-master:latest
          imagePullPolicy: IfNotPresent # IfNotPresent - use local built image; Always - Pull image from repo
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-cluster-configmap
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_REPLICATION_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-cluster-configmap
                  key: MYSQL_REPLICATION_USER
            - name: MYSQL_REPLICATION_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-cluster-configmap
                  key: MYSQL_REPLICATION_PASSWORD
