apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    name: mysql-master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-master-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/db_data/master
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-master-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-master-pvc
      containers:
        - name: mysql-master
          image: mysql-master:latest
          imagePullPolicy: IfNotPresent # IfNotPresent - use local built image; Always - Pull image from repo
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "10Gi"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
          envFrom:
            - configMapRef:
                name: mysql-cluster-configmap
