apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
  namespace: kafka
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: zookeeper-service
  name: kafka-zookeeper-pv
  namespace: kafka
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/kafka_data/zookeeper
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zookeeper-service
  name: kafka-zookeeper-pvc
  namespace: kafka
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      volumes:
        - name: zookeeper-data
          persistentVolumeClaim:
            claimName: kafka-zookeeper-pvc
      containers:
        - image: bitnami/zookeeper:3.9.1
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: 'yes'
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
          volumeMounts:
            - mountPath: /bitnami
              name: zookeeper-data
