#!/bin/bash

export MYSQL_PWD=${MYSQL_ROOT_PASSWORD}
mysql -uroot -e \
      "
      CREATE USER IF NOT EXISTS '${MYSQL_REPLICATION_USER}'@'%' IDENTIFIED BY '${MYSQL_REPLICATION_PASSWORD}';
      GRANT REPLICATION SLAVE ON *.* TO '${MYSQL_REPLICATION_USER}'@'%';
      FLUSH PRIVILEGES;
      "
