apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cronjob-mysqlkiller
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mysqlkiller-cronjob
        spec:
          restartPolicy: Never
          containers:
            - name: mysqlkiller
              image: mysqlkiller
              imagePullPolicy: IfNotPresent
              command:
                - "./bin/mysql_killer.sh"
              envFrom:
                - configMapRef:
                    name: app-cronjob-configmap
