apiVersion: v1
kind: Service
metadata:
  name: mail-service
  labels:
    name: mail-service
spec:
  ports:
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: stmp
    - port: 8025
      targetPort: 8025
      protocol: TCP
      name: web-ui
  type: NodePort
  selector:
    name: mail-service

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mail-service
  labels:
    name: mail-service
spec:
  replicas: 1
  selector:
    name: mail-service
  template:
    metadata:
      labels:
        name: mail-service
    spec:
      containers:
        - name: mail-service
          image: mailhog/mailhog:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64M"
            limits:
              memory: "128M"
          ports:
            - containerPort: 1025
            - containerPort: 8025
