apiVersion: v1
kind: Service
metadata:
  name: local-s3
  labels:
    name: local-s3
spec:
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    name: local-s3

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-s3-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  hostPath:
    path: /data/s3_data
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-s3-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-s3
  labels:
    name: local-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      name: local-s3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: local-s3
    spec:
      volumes:
        - name: s3-data
          persistentVolumeClaim:
            claimName: local-s3-pvc
      containers:
        - name: local-s3
          image: luofuxiang/local-s3:native-1.12.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512M"
            limits:
              memory: "2Gi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: s3-data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: local-s3-configmap
